check dots in titles
eugenp/blogwatch pull request #69
Opened 2022-02-13 19:29 UTC by ibrahni

2022-02-15 10:46 UTC, asif-anwar requested changes

2022-02-15 10:46 UTC, asif-anwar commented on src/test/java/com/baeldung/selenium/common/ArticlesUITest.java
> +                final List<String> invalidDotsInTitles = page.findTitlesWithInvalidDots();
@ibrahni Can you check whether you have a committed `page.findTitlesWithInvalidDots()` as I can't find it in the changed files.
We also need to make sure that we don't execute the below logic twice. 

```
 List<String> invalidTitles = new ArrayList<>();
        List<WebElement> webElements = this.getWebDriver().findElements(By.xpath("(//section//h2[not(ancestor::section[contains(@class,'further-reading-posts')] )]) | (//section//h3[not(ancestor::div[contains(@class,'after-post-widgets')] )])"));
        webElements.parallelStream().forEach(webElement -> {
            String title = webElement.getText();
            List<String> tokens = Utils.titleTokenizer(title);
            List<String> emphasizedAndItalicTagValues = Utils.getEMAndItalicTagValues(webElement.getAttribute("innerHTML"));
```

2022-02-15 19:53 UTC, ibrahni commented on src/test/java/com/baeldung/selenium/common/ArticlesUITest.java
> +                final List<String> invalidDotsInTitles = page.findTitlesWithInvalidDots();
@asif-anwar you were right, i missed adding the file with git, 
I have used the forLoop just once

2022-02-16 06:25 UTC, asif-anwar approved these changes

2022-02-16 06:25 UTC, merged